markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  line_numbers: false

  coderay:
    wrap: div
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class
